version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leska
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - my_pgdata:/var/lib/postgresql/data

volumes:
  my_pgdata: